/*
 * TIMER_config.h
 *
 *  Created on: Sep 4, 2025
 *      Author: SAGDA
 */

#ifndef MCAL_TIMER_DRIVER_TIMER_CONFIG_H_
#define MCAL_TIMER_DRIVER_TIMER_CONFIG_H_

typedef enum{
	NORMAL, PWM_PHASE_CORRECT, CTC, FAST_PWM
}WAVE_FORM_GENERATION_MODE_SELECT;

typedef enum{
	OC0_CTC_NORTMAL, TOGGLE_OC0, CLEAR_OC0, SET_OC0
}TIMER0_CTC_MODE_SELECT;

typedef enum{
	FAST_PWM_NORMAL, NON_INVERTING_MODE, INVERTING_MODE
}FAST_PWM_MODE_SELECT;

typedef enum{
	PHASE_CORRECT_PWM_NORMAL, CLEAR_UPCOUNTING_MODE, SET_UPCOUNTING_MODE
}PHASE_CORRECT_PWM_MODE_SELECT;
typedef enum{
	NO_CLOCK, NO_PRESCALER, PRESCALER_8, PRESCALER_32, PRESCALER_64,PRESCALER_128, PRESCALER_256,PRESCALER_1024
}CLOCK_SELECT;

typedef enum{
	DISABLE , ENABLE
}STATE;

#endif /* MCAL_TIMER_DRIVER_TIMER_CONFIG_H_ */
